// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rctemzwzpfntufjamgtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdGVtend6cGZudHVmamFtZ3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTgxMjQsImV4cCI6MjA2NDY3NDEyNH0.EKelmsw1hmuBirzecJ3_SXC7o6tCvM1C0Yuyzxq5b5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);